### ISSUE TITLE
exception if no layer is specified in statBin

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/kandy#138]
reproduce: 
```
val df = dataFrameOf("col1" to listOf(1, 2, 3, 1))

df.plot {
    statBin("col1") {
         x(Stat.BINS)
         y(Stat.COUNT)
    }
}
```

exception:
```
invalid column id
java.lang.IllegalStateException: invalid column id
	at org.jetbrains.kotlinx.kandy.dsl.internal.DatasetHandler.takeColumn(DatasetHandler.kt:59)
	at org.jetbrains.kotlinx.kandy.dsl.internal.BindingContext$DefaultImpls.addPositionalMapping(contexts.kt:194)
	at org.jetbrains.kotlinx.kandy.dsl.internal.PlotContext$DefaultImpls.addPositionalMapping(contexts.kt:102)
	at org.jetbrains.kotlinx.kandy.dsl.internal.LayerPlotContext$DefaultImpls.addPositionalMapping(contexts.kt:117)
	at org.jetbrains.kotlinx.kandy.dsl.internal.DataFramePlotContext.addPositionalMapping(DataFramePlotContext.kt:22)
	at org.jetbrains.kotlinx.kandy.letsplot.XyKt.x(xy.kt:21)
	at org.jetbrains.kotlinx.kandy.letsplot.XyKt.x$default(xy.kt:17)
	at Line_379_jupyter.<init>(Line_379.jupyter.kts:3)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.evalWithConfigAndOtherScriptsResults(BasicJvmScriptEvaluator.kt:105)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke$suspendImpl(BasicJvmScriptEvaluator.kt:47)
	at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke(BasicJvmScriptEvaluator.kt)
	at kotlin.script.experimental.jvm.BasicJvmReplEvaluator.eval(BasicJvmReplEvaluator.kt:49)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl$eval$resultWithDiagnostics$1.invokeSuspend(InternalEvaluatorImpl.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.jetbrains.kotlinx.jupyter.repl.impl.InternalEvaluatorImpl.eval(InternalEvaluatorImpl.kt:103)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$execute$1$result$1.invoke(CellExecutorImpl.kt:75)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl$execute$1$result$1.invoke(CellExecutorImpl.kt:73)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withHost(repl.kt:658)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute(CellExecutorImpl.kt:73)
	at org.jetbrains.kotlinx.jupyter.repl.CellExecutor$DefaultImpls.execute$default(CellExecutor.kt:15)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:471)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:462)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withEvalContext(repl.kt:425)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.evalEx(repl.kt:462)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:318)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:312)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:37)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:32)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by AndreiKingsley** [comment]
It's not bug.
Global mappings work only on the top plot context and only with main dataset.
`Plot.Context.x()` must be forbidden in inner contexts with dsl markers.

**Comment by devcrocod** [comment]
I see, but I can still write like this:
```
df.plot {
    x("cnt")
    statBin(cnt) {
        y(Stat.BINS)
        bars {}
    }
}
```

and I get the same result
```
invalid column id
java.lang.IllegalStateException: invalid column id
	at org.jetbrains.kotlinx.kandy.dsl.internal.DatasetHandler.takeColumn(DatasetHandler.kt:59)
	at org.jetbrains.kotlinx.kandy.dsl.internal.BindingContext$DefaultImpls.addPositionalMapping(contexts.kt:194)
	at org.jetbrains.kotlinx.kandy.dsl.internal.PlotContext$DefaultImpls.addPositionalMapping(contexts.kt:102)
	at org.jetbrains.kotlinx.kandy.dsl.internal.LayerPlotContext$DefaultImpls.addPositionalMapping(contexts.kt:117)
	at org.jetbrains.kotlinx.kandy.dsl.internal.DataFramePlotContext.addPositionalMapping(DataFramePlotContext.kt:22)
	at org.jetbrains.kotlinx.kandy.letsplot.XyKt.y(xy.kt:81)
	at org.jetbrains.kotlinx.kandy.letsplot.XyKt.y$default(xy.kt:77)
	at Line_599_jupyter.<init>(Line_599.jupyter.kts:4)
```

**Comment by AndreiKingsley** [comment]
right, because df has no `Stat.BINS` column. `x()` and `y()` works only in top context with its dataset

**Comment by AndreiKingsley** [comment]
they should not be available in other contexts

**Comment by devcrocod** [comment]
Sorry, I originally attached the wrong example

**Comment by AndreiKingsley** [comment]
You just don't have the `StatBinContext.y()` function at all. DSL does not work properly here because there are no dsl markers.
