### ISSUE TITLE
%use kandy in Kotlin Notebooks doesn't work

### ISSUE THREAD

**Issue by etolstoy** [Kotlin/kandy#203]
## **Describe the bug**
Installing Kandy with `%use` notation results in an error `Unknown library 'kandy@default'`. It's also not suggested with autocompletion, though Kandy README file states that it should work.

## **To Reproduce**
1. Create a Kotlin Notebook.
2. Add a line `%use kandy`.
3. Run cell.

## **Actual Behavior**
```
Failed to process '%use kandy' command. Unknown library 'kandy@default'
org.jetbrains.kotlinx.jupyter.exceptions.ReplException: Unknown library 'kandy@default'
org.jetbrains.kotlinx.jupyter.exceptions.ReplPreprocessingException: Failed to process '%use kandy' command. Unknown library 'kandy@default'
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler.handle(AbstractMagicsHandler.kt:51)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsProcessor$Companion.processSingleMagic(AbstractMagicsProcessor.kt:66)
	at org.jetbrains.kotlinx.jupyter.magics.MagicsProcessor.processMagics(MagicsProcessor.kt:14)
	at org.jetbrains.kotlinx.jupyter.magics.MagicsProcessor.processMagics$default(MagicsProcessor.kt:10)
	at org.jetbrains.kotlinx.jupyter.magics.MagicsProcessor.process(MagicsProcessor.kt:20)
	at org.jetbrains.kotlinx.jupyter.magics.CompoundCodePreprocessor.process(CompoundCodePreprocessor.kt:18)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute(CellExecutorImpl.kt:56)
	at org.jetbrains.kotlinx.jupyter.repl.CellExecutor$DefaultImpls.execute$default(CellExecutor.kt:15)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:460)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:449)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withEvalContext(repl.kt:413)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.evalEx(repl.kt:449)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.eval(repl.kt:501)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:318)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:317)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:33)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:31)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: org.jetbrains.kotlinx.jupyter.exceptions.ReplException: Unknown library 'kandy@default'
	at org.jetbrains.kotlinx.jupyter.libraries.LibrariesProcessorImpl.processNewLibraries(LibrariesProcessorImpl.kt:39)
	at org.jetbrains.kotlinx.jupyter.magics.UseMagicsHandler.handleUse(UseMagicsHandler.kt:15)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler$callbackMap$1.invoke(AbstractMagicsHandler.kt:26)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler$callbackMap$1.invoke(AbstractMagicsHandler.kt:26)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler.handle(AbstractMagicsHandler.kt:62)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler.handle(AbstractMagicsHandler.kt:48)
```

## **Library Version, Tool version, and Environment**
- IDE version: IntelliJ IDEA 2023.1 Ultimate Edition, Build #IU-231.8109.175
- Kotlin Notebooks plugin 231.8109.175

**Comment by etolstoy** [comment]
Works in the latest plugin and IDEA version.
