### ISSUE TITLE
[BUG] %use kandy fails in IntelliJ

### ISSUE THREAD

**Issue by ge0ffrey** [Kotlin/kandy#288]
![image](https://github.com/Kotlin/kandy/assets/176880/8ec23a85-443a-495a-80fa-fdb81d479a3a)

Latest Intellij, all plugins up to date.
Does not reproduce on my other Linux machine.

IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```
Failed to process '%use kandy' command. Unknown library 'kandy@default'
org.jetbrains.kotlinx.jupyter.exceptions.ReplException: Unknown library 'kandy@default'
org.jetbrains.kotlinx.jupyter.exceptions.ReplPreprocessingException: Failed to process '%use kandy' command. Unknown library 'kandy@default'
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler.handle(AbstractMagicsHandler.kt:51)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsProcessor$Companion.processSingleMagic(AbstractMagicsProcessor.kt:66)
	at org.jetbrains.kotlinx.jupyter.magics.MagicsProcessor.processMagics(MagicsProcessor.kt:14)
	at org.jetbrains.kotlinx.jupyter.magics.MagicsProcessor.processMagics$default(MagicsProcessor.kt:10)
	at org.jetbrains.kotlinx.jupyter.magics.MagicsProcessor.process(MagicsProcessor.kt:20)
	at org.jetbrains.kotlinx.jupyter.magics.CompoundCodePreprocessor.process(CompoundCodePreprocessor.kt:18)
	at org.jetbrains.kotlinx.jupyter.repl.impl.CellExecutorImpl.execute(CellExecutorImpl.kt:56)
	at org.jetbrains.kotlinx.jupyter.repl.CellExecutor$DefaultImpls.execute$default(CellExecutor.kt:15)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:451)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl$evalEx$1.invoke(repl.kt:440)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.withEvalContext(repl.kt:404)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.evalEx(repl.kt:440)
	at org.jetbrains.kotlinx.jupyter.ReplForJupyterImpl.eval(repl.kt:492)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:321)
	at org.jetbrains.kotlinx.jupyter.messaging.ProtocolKt$shellMessagesHandler$2$res$1.invoke(protocol.kt:320)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:33)
	at org.jetbrains.kotlinx.jupyter.JupyterExecutorImpl$runExecution$execThread$1.invoke(execution.kt:31)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: org.jetbrains.kotlinx.jupyter.exceptions.ReplException: Unknown library 'kandy@default'
	at org.jetbrains.kotlinx.jupyter.libraries.LibrariesProcessorImpl.processNewLibraries(LibrariesProcessorImpl.kt:32)
	at org.jetbrains.kotlinx.jupyter.magics.UseMagicsHandler.handleUse(UseMagicsHandler.kt:15)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler$callbackMap$1.invoke(AbstractMagicsHandler.kt:26)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler$callbackMap$1.invoke(AbstractMagicsHandler.kt:26)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler.handle(AbstractMagicsHandler.kt:62)
	at org.jetbrains.kotlinx.jupyter.magics.AbstractMagicsHandler.handle(AbstractMagicsHandler.kt:48)
```

**Comment by ge0ffrey** [comment]
It looks like somehow it uses an old jupyter version?
![image](https://github.com/Kotlin/kandy/assets/176880/fa55803b-d042-416d-b2f6-5b1e77847377)

Yet, I didn't do anything fancy (that I recall). I just installed the Kotlin Notebook plugin for IntelliJ and tried it.
![image](https://github.com/Kotlin/kandy/assets/176880/ec748beb-94aa-46bb-b8e4-52413e527ac4)

**Comment by ge0ffrey** [comment]
There's something wrong with the IntelliJ updates on this machine. Closing the issue until that's been resolved. I 'll reopen if that doesn't resolve it.
